# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3934512756934f7de7d9a5edceff08344db943ece8481bf6d5e4bee64a236d5346d799e71077a77a3e502bc2ad6f163ba95b28dd30dd87493694a5ac4d5834

test:
  secret_key_base: 7a5c24ad6f5ab43b894c3cd226b5d2c9fe8650d8fb18cbc5eefa0ece23b78ca9c9c17b3d3b8288afa8f7423ec200713d63b37bbc328cc263f88b5fb7926ade11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
